### PR TITLE
Add initial SOP for returning logs

### LINKED ISSUE #3: Add page that describes SOP for returning logs to developers
This page can be added to the internal section of the staging site:

For Sage Data Hosting Site:

- Login to Sage VPN
- Go to Kibana
- Find logs associated to the submission ID specified
- ...

@thomasyu888 Can you give a shot to complete this brief SOP?

### PR DESCRIPTION
**Pull request by thomasyu888**
This is a WIP.  This is enough to start the exploration.
Fixes #3

### CODE REVIEW

**Comment by tschaffter** [comment]
@thomasyu888 I updated this branch (see commit messages)

**Comment by thomasyu888** [comment]
Screen Shot 2021-01-30 at 10 34 32 AM

A bit unfortunate....

**Comment by tschaffter** [comment]
I'll talk to James and Xa to get a license so we can fully evaluate the tool.

**Comment by thomasyu888** [comment]
One option that we have is to use the amazon hosted ELK service.. the issue with that is that it's tightly tied to amazon, but the good news is I don't need a subscription and we can evaluate the tool.

**Pull request merged**
